# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
    ]
