# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('image', models.FileField(upload_to='images/main/')),
            ],
        ),
        migrations.CreateModel(
            name='MainGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('image', models.FileField(upload_to='images/main/')),
            ],
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('image', models.FileField(upload_to='images/main/')),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='new_music.MainGenre')),
            ],
        ),
        migrations.AddField(
            model_name='artists',
            name='genre',
            field=models.ManyToManyField(help_text="Hold down 'Control', or 'Command' on a Mac, to select more than one.", related_name='artists', to='new_music.MainGenre'),
        ),
        migrations.AddField(
            model_name='artists',
            name='subgenre',
            field=models.ManyToManyField(blank=True, help_text="Hold down 'Control', or 'Command' on a Mac, to select more than one.", related_name='artists', to='new_music.SubGenre'),
        ),
    ]
