# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainGenres',
            new_name='MainGenre',
        ),
    ]
