# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0007_auto_20180410_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maingenre',
            name='image',
            field=models.FileField(upload_to='images/main/'),
        ),
    ]
