# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0008_auto_20180410_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='images/main/')),
                ('dom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='new_music.MainGenre')),
            ],
        ),
    ]
