# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0009_subgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maingenre',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
