# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0010_auto_20180411_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='dom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dom_name', to='new_music.MainGenre'),
        ),
    ]
