# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0011_auto_20180411_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='dom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='MainGenre', to='new_music.MainGenre'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(db_column='name', max_length=50),
        ),
    ]
