# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0012_auto_20180411_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
