# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0018_auto_20180411_0949'),
    ]

    operations = [
        migrations.RenameField('SubGenre', 'name', 'subname'),
    ]
