# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0020_auto_20180411_1031'),
    ]

    operations = [
        migrations.RenameField('SubGenre', 'description', 'subdescription'),
        migrations.RenameField('SubGenre', 'image', 'subimage'),
    ]
