# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0021_auto_20180411_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('image', models.FileField(upload_to='images/main/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_music.MainGenre')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_music.SubGenre')),
            ],
        ),
    ]
