# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0022_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='subgenre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='new_music.SubGenre'),
        ),
    ]
