# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0024_auto_20180411_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='new_music.MainGenre'),
        ),
    ]
