# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0025_auto_20180412_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='genre',
        ),
        migrations.AddField(
            model_name='artists',
            name='genre',
            field=models.ManyToManyField(to='new_music.MainGenre'),
        ),
        migrations.RemoveField(
            model_name='artists',
            name='subgenre',
        ),
        migrations.AddField(
            model_name='artists',
            name='subgenre',
            field=models.ManyToManyField(to='new_music.SubGenre'),
        ),
    ]
