# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0026_auto_20180412_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='genre',
            field=models.ManyToManyField(related_name='artists', to='new_music.MainGenre'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='new_music.SubGenre'),
        ),
    ]
