# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0028_auto_20180412_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='genre',
            field=models.ManyToManyField(help_text="Hold down 'Control', or 'Command' on a Mac, to select more than one.", related_name='artists', to='new_music.MainGenre'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='subgenre',
            field=models.ManyToManyField(blank=True, help_text="Hold down 'Control', or 'Command' on a Mac, to select more than one.", related_name='artists', to='new_music.SubGenre'),
        ),
    ]
