# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0029_auto_20180413_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgenre',
            old_name='subdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subgenre',
            old_name='dom',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='subgenre',
            old_name='subimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='subgenre',
            old_name='subname',
            new_name='name',
        ),
    ]
