# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('date', models.DateTimeField(help_text='Time is in 24 hour time!')),
                ('posttime', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(help_text='Where is the event?', max_length=400)),
                ('max_people', models.IntegerField(help_text='How many people are allowed?')),
                ('people_going', models.IntegerField(default=0, help_text='How many people are already going?')),
                ('currency', models.CharField(default='EUR', help_text='What currency is it? IE. USD, EUR, GBP ect.', max_length=4)),
                ('admission', models.DecimalField(decimal_places=2, default=0.0, help_text='Is there a cost to enter?', max_digits=8)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_music.MainGenre')),
                ('subgenre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_music.SubGenre')),
            ],
        ),
    ]
