# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('date', models.DateTimeField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=400)),
                ('max_people', models.IntegerField()),
            ],
        ),
    ]
