# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='', max_length=100),
        ),
    ]
