# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0002_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='posttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
