# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0002_auto_20180413_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Year-Month-Day Time (2018-03-22 22:30 = March 22, 2018, 10:30PM), Time is in 24 hour time!'),
        ),
    ]
