# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0003_event_posttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
