# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0004_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='people_going',
            field=models.IntegerField(default=0),
        ),
    ]
