# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0005_event_people_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addmission',
            field=models.IntegerField(default=0.0, help_text='Is there a cost to enter?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(help_text='Where is the event?', max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Time is in 24 hour time!'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_people',
            field=models.IntegerField(help_text='How many people are allowed?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='people_going',
            field=models.IntegerField(default=0, help_text='How many people are already going?'),
        ),
    ]
