# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0007_event_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='addmission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Is there a cost to enter?', max_digits=8),
        ),
    ]
