# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate_music', '0008_auto_20180412_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='addmission',
            new_name='admission',
        ),
    ]
