# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0025_auto_20180412_1010'),
        ('locate_music', '0009_auto_20180412_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_music.MainGenre'),
        ),
        migrations.AddField(
            model_name='event',
            name='subgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_music.SubGenre'),
        ),
    ]
